-- =============================================================================
-- Project Gaze — PostgreSQL Schema (Integer PKs + public_id for external APIs)
--
-- This schema uses:
--   - internal auto-increment integer IDs (`id`) for joins/perf
--   - stable external string identifiers (`public_id`) for API requests
--
-- Notes:
--   - Existing auth/RLS model is preserved.
--   - References to auth.users stay UUID because Supabase Auth uses UUID user IDs.
--   - Court status is materialized on `courts.status` and starts as `unknown`
--     until the first occupancy event is processed.
-- =============================================================================


-- =============================================================================
-- 0) HELPERS
-- =============================================================================

-- Stable slug helper for generated public IDs.
CREATE OR REPLACE FUNCTION public.slugify(input text)
RETURNS text
LANGUAGE sql
IMMUTABLE
AS $$
  SELECT trim(both '-' FROM regexp_replace(lower(coalesce(input, '')), '[^a-z0-9]+', '-', 'g'));
$$;


-- =============================================================================
-- 1) PROFILES (extends Supabase Auth)
-- =============================================================================

CREATE TABLE IF NOT EXISTS profiles (
    id          UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    role        TEXT NOT NULL DEFAULT 'user' CHECK (role IN ('user', 'admin')),
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "profiles_select_own" ON profiles;
CREATE POLICY "profiles_select_own"
    ON profiles FOR SELECT
    TO authenticated
    USING (id = auth.uid());

DROP POLICY IF EXISTS "profiles_select_admin" ON profiles;
CREATE POLICY "profiles_select_admin"
    ON profiles FOR SELECT
    TO authenticated
    USING (
        EXISTS (
            SELECT 1 FROM profiles p
            WHERE p.id = auth.uid()
              AND p.role = 'admin'
        )
    );

CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
    INSERT INTO public.profiles (id, role)
    VALUES (NEW.id, 'user')
    ON CONFLICT (id) DO NOTHING;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;

CREATE TRIGGER on_auth_user_created
    AFTER INSERT ON auth.users
    FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();


-- =============================================================================
-- 2) LOCATIONS
-- =============================================================================

CREATE TABLE IF NOT EXISTS locations (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id   TEXT NOT NULL UNIQUE,
    name        TEXT NOT NULL,
    latitude    DOUBLE PRECISION NOT NULL,
    longitude   DOUBLE PRECISION NOT NULL,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE locations ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "locations_select_authenticated" ON locations;
CREATE POLICY "locations_select_authenticated"
    ON locations FOR SELECT
    TO authenticated
    USING (true);

DROP POLICY IF EXISTS "locations_insert_admin" ON locations;
CREATE POLICY "locations_insert_admin"
    ON locations FOR INSERT
    TO authenticated
    WITH CHECK (
        EXISTS (
            SELECT 1 FROM profiles
            WHERE profiles.id = auth.uid()
              AND profiles.role = 'admin'
        )
    );

DROP POLICY IF EXISTS "locations_update_admin" ON locations;
CREATE POLICY "locations_update_admin"
    ON locations FOR UPDATE
    TO authenticated
    USING (
        EXISTS (
            SELECT 1 FROM profiles
            WHERE profiles.id = auth.uid()
              AND profiles.role = 'admin'
        )
    );

DROP POLICY IF EXISTS "locations_delete_admin" ON locations;
CREATE POLICY "locations_delete_admin"
    ON locations FOR DELETE
    TO authenticated
    USING (
        EXISTS (
            SELECT 1 FROM profiles
            WHERE profiles.id = auth.uid()
              AND profiles.role = 'admin'
        )
    );


-- =============================================================================
-- 3) COURTS
-- =============================================================================

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_type t WHERE t.typname = 'court_status'
  ) THEN
    CREATE TYPE court_status AS ENUM ('unknown', 'occupied', 'available');
  END IF;
END $$;

CREATE TABLE IF NOT EXISTS courts (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id   TEXT NOT NULL UNIQUE,
    location_id BIGINT NOT NULL REFERENCES locations(id) ON DELETE CASCADE,
    name        TEXT NOT NULL,
    number      INTEGER NOT NULL,
    status      court_status NOT NULL DEFAULT 'unknown',
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),

    UNIQUE (location_id, number)
);

ALTER TABLE courts ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "courts_select_authenticated" ON courts;
CREATE POLICY "courts_select_authenticated"
    ON courts FOR SELECT
    TO authenticated
    USING (true);

DROP POLICY IF EXISTS "courts_insert_admin" ON courts;
CREATE POLICY "courts_insert_admin"
    ON courts FOR INSERT
    TO authenticated
    WITH CHECK (
        EXISTS (
            SELECT 1 FROM profiles
            WHERE profiles.id = auth.uid()
              AND profiles.role = 'admin'
        )
    );

DROP POLICY IF EXISTS "courts_update_admin" ON courts;
CREATE POLICY "courts_update_admin"
    ON courts FOR UPDATE
    TO authenticated
    USING (
        EXISTS (
            SELECT 1 FROM profiles
            WHERE profiles.id = auth.uid()
              AND profiles.role = 'admin'
        )
    );


-- =============================================================================
-- 4) SENSORS
-- =============================================================================

CREATE TABLE IF NOT EXISTS sensors (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id     TEXT NOT NULL UNIQUE,
    court_id      BIGINT REFERENCES courts(id) ON DELETE SET NULL,
    registered_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    last_seen_at  TIMESTAMPTZ
);

ALTER TABLE sensors ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "sensors_select_authenticated" ON sensors;
CREATE POLICY "sensors_select_authenticated"
    ON sensors FOR SELECT
    TO authenticated
    USING (true);

DROP POLICY IF EXISTS "sensors_update_admin" ON sensors;
CREATE POLICY "sensors_update_admin"
    ON sensors FOR UPDATE
    TO authenticated
    USING (
        EXISTS (
            SELECT 1 FROM profiles
            WHERE profiles.id = auth.uid()
              AND profiles.role = 'admin'
        )
    );


-- =============================================================================
-- 5) USER FAVORITE LOCATIONS
-- =============================================================================

CREATE TABLE IF NOT EXISTS user_favorite_locations (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    location_id BIGINT NOT NULL REFERENCES locations(id) ON DELETE CASCADE,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),

    UNIQUE (user_id, location_id)
);

ALTER TABLE user_favorite_locations ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "favorites_select_own" ON user_favorite_locations;
CREATE POLICY "favorites_select_own"
    ON user_favorite_locations FOR SELECT
    TO authenticated
    USING (user_id = auth.uid());

DROP POLICY IF EXISTS "favorites_insert_own" ON user_favorite_locations;
CREATE POLICY "favorites_insert_own"
    ON user_favorite_locations FOR INSERT
    TO authenticated
    WITH CHECK (user_id = auth.uid());

DROP POLICY IF EXISTS "favorites_delete_own" ON user_favorite_locations;
CREATE POLICY "favorites_delete_own"
    ON user_favorite_locations FOR DELETE
    TO authenticated
    USING (user_id = auth.uid());


-- =============================================================================
-- 6) EVENTS
-- =============================================================================

CREATE TABLE IF NOT EXISTS events (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_name  TEXT NOT NULL CHECK (event_name IN ('court_occupied', 'court_unoccupied')),
    timestamp   TIMESTAMPTZ NOT NULL DEFAULT now(),
    sensor_id   BIGINT NOT NULL REFERENCES sensors(id) ON DELETE CASCADE,
    court_id    BIGINT NOT NULL REFERENCES courts(id) ON DELETE CASCADE,
    payload     JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_events_court_ts
    ON events (court_id, timestamp DESC);

CREATE INDEX IF NOT EXISTS idx_events_sensor_ts
    ON events (sensor_id, timestamp DESC);

ALTER TABLE events ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "events_select_authenticated" ON events;
CREATE POLICY "events_select_authenticated"
    ON events FOR SELECT
    TO authenticated
    USING (true);


-- =============================================================================
-- 7) ENABLE REALTIME
-- =============================================================================

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_publication_tables
        WHERE pubname = 'supabase_realtime'
          AND schemaname = 'public'
          AND tablename = 'events'
    ) THEN
        ALTER PUBLICATION supabase_realtime ADD TABLE events;
    END IF;
END $$;


-- =============================================================================
-- 8) public_id GENERATORS + TRIGGERS
-- =============================================================================

-- LOCATION public_id: loc-<slug(name)>[-<id>]
CREATE OR REPLACE FUNCTION public.set_location_public_id()
RETURNS TRIGGER AS $$
DECLARE
  base_slug text;
BEGIN
  IF NEW.public_id IS NULL OR NEW.public_id = '' THEN
    base_slug := slugify(NEW.name);
    IF base_slug = '' THEN
      base_slug := 'location';
    END IF;

    NEW.public_id := 'loc-' || base_slug;

    -- Ensure uniqueness; append internal id if collision.
    IF EXISTS (SELECT 1 FROM locations l WHERE l.public_id = NEW.public_id) THEN
      NEW.public_id := 'loc-' || base_slug || '-' || NEW.id::text;
    END IF;
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_locations_public_id ON locations;
CREATE TRIGGER trg_locations_public_id
BEFORE INSERT ON locations
FOR EACH ROW
EXECUTE FUNCTION public.set_location_public_id();


-- COURT public_id: court-<location_public_id>-<number>
CREATE OR REPLACE FUNCTION public.set_court_public_id()
RETURNS TRIGGER AS $$
DECLARE
  loc_pub text;
BEGIN
  IF NEW.public_id IS NULL OR NEW.public_id = '' THEN
    SELECT public_id INTO loc_pub FROM locations WHERE id = NEW.location_id;
    IF loc_pub IS NULL THEN
      loc_pub := 'loc';
    END IF;
    NEW.public_id := 'court-' || loc_pub || '-' || NEW.number::text;
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_courts_public_id ON courts;
CREATE TRIGGER trg_courts_public_id
BEFORE INSERT ON courts
FOR EACH ROW
EXECUTE FUNCTION public.set_court_public_id();


-- SENSOR public_id: sensor-<id> by default
CREATE OR REPLACE FUNCTION public.set_sensor_public_id()
RETURNS TRIGGER AS $$
BEGIN
  IF NEW.public_id IS NULL OR NEW.public_id = '' THEN
    NEW.public_id := 'sensor-' || NEW.id::text;
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_sensors_public_id ON sensors;
CREATE TRIGGER trg_sensors_public_id
BEFORE INSERT ON sensors
FOR EACH ROW
EXECUTE FUNCTION public.set_sensor_public_id();


-- =============================================================================
-- 9) OPTIONAL DEV SEED
-- =============================================================================
-- Example:
-- INSERT INTO locations (public_id, name, latitude, longitude)
-- VALUES ('loc-los-altos-high', 'Los Altos High School', 37.3782, -122.1180)
-- ON CONFLICT (public_id) DO NOTHING;
--
-- INSERT INTO courts (public_id, location_id, name, number)
-- SELECT
--   'court-loc-los-altos-high-' || gs::text,
--   l.id,
--   'Court ' || gs::text,
--   gs
-- FROM generate_series(1, 8) gs
-- CROSS JOIN LATERAL (
--   SELECT id FROM locations WHERE public_id = 'loc-los-altos-high' LIMIT 1
-- ) l
-- ON CONFLICT (public_id) DO NOTHING;
